// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v5.29.2
// source: oneof.proto

package protov1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OneofExample struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 普通字段
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// oneof 字段组
	//
	// Types that are valid to be assigned to ContactMethod:
	//
	//	*OneofExample_Email
	//	*OneofExample_Phone
	//	*OneofExample_Address
	ContactMethod isOneofExample_ContactMethod `protobuf_oneof:"contact_method"`
	// 另一个 oneof 组
	//
	// Types that are valid to be assigned to PaymentMethod:
	//
	//	*OneofExample_CreditCard
	//	*OneofExample_BankAccount
	//	*OneofExample_DigitalWallet
	PaymentMethod isOneofExample_PaymentMethod `protobuf_oneof:"payment_method"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OneofExample) Reset() {
	*x = OneofExample{}
	mi := &file_oneof_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OneofExample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OneofExample) ProtoMessage() {}

func (x *OneofExample) ProtoReflect() protoreflect.Message {
	mi := &file_oneof_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OneofExample.ProtoReflect.Descriptor instead.
func (*OneofExample) Descriptor() ([]byte, []int) {
	return file_oneof_proto_rawDescGZIP(), []int{0}
}

func (x *OneofExample) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OneofExample) GetContactMethod() isOneofExample_ContactMethod {
	if x != nil {
		return x.ContactMethod
	}
	return nil
}

func (x *OneofExample) GetEmail() string {
	if x != nil {
		if x, ok := x.ContactMethod.(*OneofExample_Email); ok {
			return x.Email
		}
	}
	return ""
}

func (x *OneofExample) GetPhone() string {
	if x != nil {
		if x, ok := x.ContactMethod.(*OneofExample_Phone); ok {
			return x.Phone
		}
	}
	return ""
}

func (x *OneofExample) GetAddress() string {
	if x != nil {
		if x, ok := x.ContactMethod.(*OneofExample_Address); ok {
			return x.Address
		}
	}
	return ""
}

func (x *OneofExample) GetPaymentMethod() isOneofExample_PaymentMethod {
	if x != nil {
		return x.PaymentMethod
	}
	return nil
}

func (x *OneofExample) GetCreditCard() *CreditCard {
	if x != nil {
		if x, ok := x.PaymentMethod.(*OneofExample_CreditCard); ok {
			return x.CreditCard
		}
	}
	return nil
}

func (x *OneofExample) GetBankAccount() *BankAccount {
	if x != nil {
		if x, ok := x.PaymentMethod.(*OneofExample_BankAccount); ok {
			return x.BankAccount
		}
	}
	return nil
}

func (x *OneofExample) GetDigitalWallet() *DigitalWallet {
	if x != nil {
		if x, ok := x.PaymentMethod.(*OneofExample_DigitalWallet); ok {
			return x.DigitalWallet
		}
	}
	return nil
}

type isOneofExample_ContactMethod interface {
	isOneofExample_ContactMethod()
}

type OneofExample_Email struct {
	Email string `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

type OneofExample_Phone struct {
	Phone string `protobuf:"bytes,3,opt,name=phone,proto3,oneof"`
}

type OneofExample_Address struct {
	Address string `protobuf:"bytes,4,opt,name=address,proto3,oneof"`
}

func (*OneofExample_Email) isOneofExample_ContactMethod() {}

func (*OneofExample_Phone) isOneofExample_ContactMethod() {}

func (*OneofExample_Address) isOneofExample_ContactMethod() {}

type isOneofExample_PaymentMethod interface {
	isOneofExample_PaymentMethod()
}

type OneofExample_CreditCard struct {
	CreditCard *CreditCard `protobuf:"bytes,5,opt,name=credit_card,json=creditCard,proto3,oneof"`
}

type OneofExample_BankAccount struct {
	BankAccount *BankAccount `protobuf:"bytes,6,opt,name=bank_account,json=bankAccount,proto3,oneof"`
}

type OneofExample_DigitalWallet struct {
	DigitalWallet *DigitalWallet `protobuf:"bytes,7,opt,name=digital_wallet,json=digitalWallet,proto3,oneof"`
}

func (*OneofExample_CreditCard) isOneofExample_PaymentMethod() {}

func (*OneofExample_BankAccount) isOneofExample_PaymentMethod() {}

func (*OneofExample_DigitalWallet) isOneofExample_PaymentMethod() {}

type CreditCard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Number        string                 `protobuf:"bytes,1,opt,name=number,proto3" json:"number,omitempty"`
	Expiry        string                 `protobuf:"bytes,2,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Cvv           string                 `protobuf:"bytes,3,opt,name=cvv,proto3" json:"cvv,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditCard) Reset() {
	*x = CreditCard{}
	mi := &file_oneof_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditCard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditCard) ProtoMessage() {}

func (x *CreditCard) ProtoReflect() protoreflect.Message {
	mi := &file_oneof_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditCard.ProtoReflect.Descriptor instead.
func (*CreditCard) Descriptor() ([]byte, []int) {
	return file_oneof_proto_rawDescGZIP(), []int{1}
}

func (x *CreditCard) GetNumber() string {
	if x != nil {
		return x.Number
	}
	return ""
}

func (x *CreditCard) GetExpiry() string {
	if x != nil {
		return x.Expiry
	}
	return ""
}

func (x *CreditCard) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

type BankAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountNumber string                 `protobuf:"bytes,1,opt,name=account_number,json=accountNumber,proto3" json:"account_number,omitempty"`
	RoutingNumber string                 `protobuf:"bytes,2,opt,name=routing_number,json=routingNumber,proto3" json:"routing_number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BankAccount) Reset() {
	*x = BankAccount{}
	mi := &file_oneof_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BankAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BankAccount) ProtoMessage() {}

func (x *BankAccount) ProtoReflect() protoreflect.Message {
	mi := &file_oneof_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BankAccount.ProtoReflect.Descriptor instead.
func (*BankAccount) Descriptor() ([]byte, []int) {
	return file_oneof_proto_rawDescGZIP(), []int{2}
}

func (x *BankAccount) GetAccountNumber() string {
	if x != nil {
		return x.AccountNumber
	}
	return ""
}

func (x *BankAccount) GetRoutingNumber() string {
	if x != nil {
		return x.RoutingNumber
	}
	return ""
}

type DigitalWallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WalletId      string                 `protobuf:"bytes,1,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DigitalWallet) Reset() {
	*x = DigitalWallet{}
	mi := &file_oneof_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DigitalWallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DigitalWallet) ProtoMessage() {}

func (x *DigitalWallet) ProtoReflect() protoreflect.Message {
	mi := &file_oneof_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DigitalWallet.ProtoReflect.Descriptor instead.
func (*DigitalWallet) Descriptor() ([]byte, []int) {
	return file_oneof_proto_rawDescGZIP(), []int{3}
}

func (x *DigitalWallet) GetWalletId() string {
	if x != nil {
		return x.WalletId
	}
	return ""
}

func (x *DigitalWallet) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type NotificationSettings struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Enabled bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	// 通知方式只能选择一种
	//
	// Types that are valid to be assigned to DeliveryMethod:
	//
	//	*NotificationSettings_Email
	//	*NotificationSettings_Sms
	//	*NotificationSettings_Push
	//	*NotificationSettings_Webhook
	DeliveryMethod isNotificationSettings_DeliveryMethod `protobuf_oneof:"delivery_method"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *NotificationSettings) Reset() {
	*x = NotificationSettings{}
	mi := &file_oneof_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationSettings) ProtoMessage() {}

func (x *NotificationSettings) ProtoReflect() protoreflect.Message {
	mi := &file_oneof_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationSettings.ProtoReflect.Descriptor instead.
func (*NotificationSettings) Descriptor() ([]byte, []int) {
	return file_oneof_proto_rawDescGZIP(), []int{4}
}

func (x *NotificationSettings) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *NotificationSettings) GetDeliveryMethod() isNotificationSettings_DeliveryMethod {
	if x != nil {
		return x.DeliveryMethod
	}
	return nil
}

func (x *NotificationSettings) GetEmail() *EmailSettings {
	if x != nil {
		if x, ok := x.DeliveryMethod.(*NotificationSettings_Email); ok {
			return x.Email
		}
	}
	return nil
}

func (x *NotificationSettings) GetSms() *SMSSettings {
	if x != nil {
		if x, ok := x.DeliveryMethod.(*NotificationSettings_Sms); ok {
			return x.Sms
		}
	}
	return nil
}

func (x *NotificationSettings) GetPush() *PushSettings {
	if x != nil {
		if x, ok := x.DeliveryMethod.(*NotificationSettings_Push); ok {
			return x.Push
		}
	}
	return nil
}

func (x *NotificationSettings) GetWebhook() *WebhookSettings {
	if x != nil {
		if x, ok := x.DeliveryMethod.(*NotificationSettings_Webhook); ok {
			return x.Webhook
		}
	}
	return nil
}

type isNotificationSettings_DeliveryMethod interface {
	isNotificationSettings_DeliveryMethod()
}

type NotificationSettings_Email struct {
	Email *EmailSettings `protobuf:"bytes,2,opt,name=email,proto3,oneof"`
}

type NotificationSettings_Sms struct {
	Sms *SMSSettings `protobuf:"bytes,3,opt,name=sms,proto3,oneof"`
}

type NotificationSettings_Push struct {
	Push *PushSettings `protobuf:"bytes,4,opt,name=push,proto3,oneof"`
}

type NotificationSettings_Webhook struct {
	Webhook *WebhookSettings `protobuf:"bytes,5,opt,name=webhook,proto3,oneof"`
}

func (*NotificationSettings_Email) isNotificationSettings_DeliveryMethod() {}

func (*NotificationSettings_Sms) isNotificationSettings_DeliveryMethod() {}

func (*NotificationSettings_Push) isNotificationSettings_DeliveryMethod() {}

func (*NotificationSettings_Webhook) isNotificationSettings_DeliveryMethod() {}

type EmailSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EmailAddress  string                 `protobuf:"bytes,1,opt,name=email_address,json=emailAddress,proto3" json:"email_address,omitempty"`
	HtmlFormat    bool                   `protobuf:"varint,2,opt,name=html_format,json=htmlFormat,proto3" json:"html_format,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmailSettings) Reset() {
	*x = EmailSettings{}
	mi := &file_oneof_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmailSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmailSettings) ProtoMessage() {}

func (x *EmailSettings) ProtoReflect() protoreflect.Message {
	mi := &file_oneof_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmailSettings.ProtoReflect.Descriptor instead.
func (*EmailSettings) Descriptor() ([]byte, []int) {
	return file_oneof_proto_rawDescGZIP(), []int{5}
}

func (x *EmailSettings) GetEmailAddress() string {
	if x != nil {
		return x.EmailAddress
	}
	return ""
}

func (x *EmailSettings) GetHtmlFormat() bool {
	if x != nil {
		return x.HtmlFormat
	}
	return false
}

type SMSSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PhoneNumber   string                 `protobuf:"bytes,1,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	CountryCode   string                 `protobuf:"bytes,2,opt,name=country_code,json=countryCode,proto3" json:"country_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SMSSettings) Reset() {
	*x = SMSSettings{}
	mi := &file_oneof_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SMSSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SMSSettings) ProtoMessage() {}

func (x *SMSSettings) ProtoReflect() protoreflect.Message {
	mi := &file_oneof_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SMSSettings.ProtoReflect.Descriptor instead.
func (*SMSSettings) Descriptor() ([]byte, []int) {
	return file_oneof_proto_rawDescGZIP(), []int{6}
}

func (x *SMSSettings) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *SMSSettings) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

type PushSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceToken   string                 `protobuf:"bytes,1,opt,name=device_token,json=deviceToken,proto3" json:"device_token,omitempty"`
	Platform      string                 `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"` // ios, android, web
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushSettings) Reset() {
	*x = PushSettings{}
	mi := &file_oneof_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSettings) ProtoMessage() {}

func (x *PushSettings) ProtoReflect() protoreflect.Message {
	mi := &file_oneof_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSettings.ProtoReflect.Descriptor instead.
func (*PushSettings) Descriptor() ([]byte, []int) {
	return file_oneof_proto_rawDescGZIP(), []int{7}
}

func (x *PushSettings) GetDeviceToken() string {
	if x != nil {
		return x.DeviceToken
	}
	return ""
}

func (x *PushSettings) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

type WebhookSettings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,2,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Secret        string                 `protobuf:"bytes,3,opt,name=secret,proto3" json:"secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebhookSettings) Reset() {
	*x = WebhookSettings{}
	mi := &file_oneof_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebhookSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebhookSettings) ProtoMessage() {}

func (x *WebhookSettings) ProtoReflect() protoreflect.Message {
	mi := &file_oneof_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebhookSettings.ProtoReflect.Descriptor instead.
func (*WebhookSettings) Descriptor() ([]byte, []int) {
	return file_oneof_proto_rawDescGZIP(), []int{8}
}

func (x *WebhookSettings) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *WebhookSettings) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *WebhookSettings) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

var File_oneof_proto protoreflect.FileDescriptor

var file_oneof_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x6f,
	0x6e, 0x65, 0x6f, 0x66, 0x2e, 0x76, 0x31, 0x22, 0xc9, 0x02, 0x0a, 0x0c, 0x4f, 0x6e, 0x65, 0x6f,
	0x66, 0x45, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x16, 0x0a, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x12, 0x1a, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x37, 0x0a, 0x0b, 0x63, 0x72, 0x65, 0x64,
	0x69, 0x74, 0x5f, 0x63, 0x61, 0x72, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43,
	0x61, 0x72, 0x64, 0x48, 0x01, 0x52, 0x0a, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72,
	0x64, 0x12, 0x3a, 0x0a, 0x0c, 0x62, 0x61, 0x6e, 0x6b, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x2e,
	0x76, 0x31, 0x2e, 0x42, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x48, 0x01,
	0x52, 0x0b, 0x62, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x40, 0x0a,
	0x0e, 0x64, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c, 0x5f, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x48, 0x01,
	0x52, 0x0d, 0x64, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x42,
	0x10, 0x0a, 0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x63, 0x74, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x42, 0x10, 0x0a, 0x0e, 0x70, 0x61, 0x79, 0x6d, 0x65, 0x6e, 0x74, 0x5f, 0x6d, 0x65, 0x74,
	0x68, 0x6f, 0x64, 0x22, 0x4e, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x43, 0x61, 0x72,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x78, 0x70,
	0x69, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x65, 0x78, 0x70, 0x69, 0x72,
	0x79, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x76, 0x76, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x63, 0x76, 0x76, 0x22, 0x5b, 0x0a, 0x0b, 0x42, 0x61, 0x6e, 0x6b, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x6e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0e, 0x72, 0x6f, 0x75,
	0x74, 0x69, 0x6e, 0x67, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x72, 0x6f, 0x75, 0x74, 0x69, 0x6e, 0x67, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x22, 0x48, 0x0a, 0x0d, 0x44, 0x69, 0x67, 0x69, 0x74, 0x61, 0x6c, 0x57, 0x61, 0x6c, 0x6c, 0x65,
	0x74, 0x12, 0x1b, 0x0a, 0x09, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x70, 0x72, 0x6f, 0x76, 0x69, 0x64, 0x65, 0x72, 0x22, 0x84, 0x02, 0x0a, 0x14, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x2f, 0x0a,
	0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6f,
	0x6e, 0x65, 0x6f, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x74,
	0x74, 0x69, 0x6e, 0x67, 0x73, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x29,
	0x0a, 0x03, 0x73, 0x6d, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x6f, 0x6e,
	0x65, 0x6f, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x4d, 0x53, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x48, 0x00, 0x52, 0x03, 0x73, 0x6d, 0x73, 0x12, 0x2c, 0x0a, 0x04, 0x70, 0x75, 0x73,
	0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x2e,
	0x76, 0x31, 0x2e, 0x50, 0x75, 0x73, 0x68, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x48,
	0x00, 0x52, 0x04, 0x70, 0x75, 0x73, 0x68, 0x12, 0x35, 0x0a, 0x07, 0x77, 0x65, 0x62, 0x68, 0x6f,
	0x6f, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x6e, 0x65, 0x6f, 0x66,
	0x2e, 0x76, 0x31, 0x2e, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x74, 0x74, 0x69,
	0x6e, 0x67, 0x73, 0x48, 0x00, 0x52, 0x07, 0x77, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x42, 0x11,
	0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x69, 0x76, 0x65, 0x72, 0x79, 0x5f, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x22, 0x55, 0x0a, 0x0d, 0x45, 0x6d, 0x61, 0x69, 0x6c, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e,
	0x67, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x5f, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x65, 0x6d, 0x61, 0x69, 0x6c,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x68, 0x74, 0x6d, 0x6c, 0x5f,
	0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x68, 0x74,
	0x6d, 0x6c, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x22, 0x53, 0x0a, 0x0b, 0x53, 0x4d, 0x53, 0x53,
	0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70,
	0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x4d, 0x0a,
	0x0c, 0x50, 0x75, 0x73, 0x68, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x12, 0x21, 0x0a,
	0x0c, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x74, 0x66, 0x6f, 0x72, 0x6d, 0x22, 0xb9, 0x01, 0x0a,
	0x0f, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x40, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x2e, 0x76, 0x31, 0x2e, 0x57,
	0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x53, 0x65, 0x74, 0x74, 0x69, 0x6e, 0x67, 0x73, 0x2e, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x1a, 0x3a, 0x0a, 0x0c,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14,
	0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6c, 0x69, 0x6e, 0x32, 0x31, 0x31, 0x2f, 0x67,
	0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x76, 0x31, 0x3b, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_oneof_proto_rawDescOnce sync.Once
	file_oneof_proto_rawDescData = file_oneof_proto_rawDesc
)

func file_oneof_proto_rawDescGZIP() []byte {
	file_oneof_proto_rawDescOnce.Do(func() {
		file_oneof_proto_rawDescData = protoimpl.X.CompressGZIP(file_oneof_proto_rawDescData)
	})
	return file_oneof_proto_rawDescData
}

var file_oneof_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_oneof_proto_goTypes = []any{
	(*OneofExample)(nil),         // 0: oneof.v1.OneofExample
	(*CreditCard)(nil),           // 1: oneof.v1.CreditCard
	(*BankAccount)(nil),          // 2: oneof.v1.BankAccount
	(*DigitalWallet)(nil),        // 3: oneof.v1.DigitalWallet
	(*NotificationSettings)(nil), // 4: oneof.v1.NotificationSettings
	(*EmailSettings)(nil),        // 5: oneof.v1.EmailSettings
	(*SMSSettings)(nil),          // 6: oneof.v1.SMSSettings
	(*PushSettings)(nil),         // 7: oneof.v1.PushSettings
	(*WebhookSettings)(nil),      // 8: oneof.v1.WebhookSettings
	nil,                          // 9: oneof.v1.WebhookSettings.HeadersEntry
}
var file_oneof_proto_depIdxs = []int32{
	1, // 0: oneof.v1.OneofExample.credit_card:type_name -> oneof.v1.CreditCard
	2, // 1: oneof.v1.OneofExample.bank_account:type_name -> oneof.v1.BankAccount
	3, // 2: oneof.v1.OneofExample.digital_wallet:type_name -> oneof.v1.DigitalWallet
	5, // 3: oneof.v1.NotificationSettings.email:type_name -> oneof.v1.EmailSettings
	6, // 4: oneof.v1.NotificationSettings.sms:type_name -> oneof.v1.SMSSettings
	7, // 5: oneof.v1.NotificationSettings.push:type_name -> oneof.v1.PushSettings
	8, // 6: oneof.v1.NotificationSettings.webhook:type_name -> oneof.v1.WebhookSettings
	9, // 7: oneof.v1.WebhookSettings.headers:type_name -> oneof.v1.WebhookSettings.HeadersEntry
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	8, // [8:8] is the sub-list for extension type_name
	8, // [8:8] is the sub-list for extension extendee
	0, // [0:8] is the sub-list for field type_name
}

func init() { file_oneof_proto_init() }
func file_oneof_proto_init() {
	if File_oneof_proto != nil {
		return
	}
	file_oneof_proto_msgTypes[0].OneofWrappers = []any{
		(*OneofExample_Email)(nil),
		(*OneofExample_Phone)(nil),
		(*OneofExample_Address)(nil),
		(*OneofExample_CreditCard)(nil),
		(*OneofExample_BankAccount)(nil),
		(*OneofExample_DigitalWallet)(nil),
	}
	file_oneof_proto_msgTypes[4].OneofWrappers = []any{
		(*NotificationSettings_Email)(nil),
		(*NotificationSettings_Sms)(nil),
		(*NotificationSettings_Push)(nil),
		(*NotificationSettings_Webhook)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_oneof_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_oneof_proto_goTypes,
		DependencyIndexes: file_oneof_proto_depIdxs,
		MessageInfos:      file_oneof_proto_msgTypes,
	}.Build()
	File_oneof_proto = out.File
	file_oneof_proto_rawDesc = nil
	file_oneof_proto_goTypes = nil
	file_oneof_proto_depIdxs = nil
}
